//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication30.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblResult
    {
        public int RES_ID { get; set; }
        public string RES_NAME { get; set; }
        public string RES_ENROLL { get; set; }
        public Nullable<double> RES_MARKS { get; set; }
    }
}
