//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication30.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStudent
    {
        public int STD_ID { get; set; }
        public string STD_NAME { get; set; }
        public string STD_ENROLL { get; set; }
        public string STD_PWD { get; set; }
    }
}
